spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:file:~/order;INIT=CREATE SCHEMA IF NOT EXISTS MS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false

  jms:
    pub-sub-domain: false

  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 8080
  servlet:
    context-path: /app

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false

info:
  app:
    name: Application
    description: Order Application
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
